<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <RootNamespace>Backend.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="Microsoft.AspNet.WebApi.Client"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit3TestAdapter"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Backend\Backend\Backend.csproj"/>
    </ItemGroup>

</Project>