using Backend.Domain;
using FluentAssertions;
using NUnit.Framework;

namespace Backend.Tests;

public class UnitTests
{
    [Test]
    public void TasksHaveAnAutogeneratedId()
    {
        new Task("Any", "Any").Id.Should().NotBeEmpty();
    }
}