using System;
using Backend.Domain;
using FluentAssertions;
using NUnit.Framework;
using static Backend.Tests.TestAPI.TaskFactory;

namespace Backend.Tests;

public class UnitTests
{
    [Test]
    public void TasksHaveAnAutogeneratedId()
    {
        new Task("Any", "Any").Id.Should().NotBeEmpty();
    }

    [Test]
    public void TasksWithSameName_AreNotConsideredTheSame()
    {
        const string aName = "A name";

        BackendTask(aName)
            .Equals(BackendTask(aName))
            .Should().BeFalse();
    }

    [Test]
    public void TasksWithSameId_AreConsideredTheSame()
    {
        var anId = Guid.NewGuid();
        const string aName = "A name";

        BackendTask(id: anId, aName)
            .Equals(BackendTask(id: anId, aName))
            .Should().BeTrue();
    }
}