@Backend_HostAddress = http://localhost:5045

GET {{Backend_HostAddress}}/health/
Accept: application/json

###

GET {{Backend_HostAddress}}/project/tasks/
Accept: application/json

###

POST {{Backend_HostAddress}}/project/tasks/
Accept: application/json
Content-Type: application/json

{
  "Name": "Any",
  "Description": "Any"
}
