@startuml
skin rose

'https://plantuml.com/component-diagram

node Client {
    [Desktop]
    [FileSystem]
    [Desktop] ..> [FileSystem] : use
}

node Cloud {
    REST -- [Backend]
    [Desktop] .> REST
    
    [Backend] --> [ASP.NET Controllers]
    [ASP.NET Controllers] --> [EntityFramework]
    
    database Database
    [EntityFramework] --> Database
}

@enduml