@startuml
skin rose

'https://plantuml.com/use-case-diagram

left to right direction

actor Stakeholder
actor User
actor ProductOwner

Stakeholder <|-- User
Stakeholder <|-- ProductOwner

package Task {
    User -- (CRUD task)
    (Propose task) -- ProductOwner
    (Rate task) -- Stakeholder
    (Comment task) -- Stakeholder
}

package Project {
    (CRUD project)
    (View tasks as prioritized list)

    (Define tasks order <<prioritization>>)

    (Define project tree)
    (View project tree)
    (View tasks in project tree structure)
    
    (View daily summary)
}

User -- Project

package FlowMetrics {
     (View flow efficiency)
     (View cycle time)
     (View task aging)
     (Config trust %)
     (Config date range)
}
 FlowMetrics - Stakeholder

@enduml