# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run e2e tests

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Node.js (required for Appium)
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.x

      - name: Setup Appium Server
        run: npm install -g appium

      - name: Setup Appium Windows Driver
        run: appium driver install windows

      - name: Set APPIUM_HOST
        run: echo "APPIUM_HOST=http://127.0.0.1:4724" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName~e2e"
